# Hook options
hook:
  bukkit:
    # Should we hook the Bukkit event?
    enabled: true
    # Should we call the BukkitListenerEvent?
    call-event: true
    # Should we use reflection to get player in unknown events?
    use-reflection-to-get-event-player: true

  netty:
    # Should we hook the netty pipeline?
    enabled: true
    # Should we call the NettyCodecEvent?
    call-event: false