name: PluginHooker
version: '${project.version}'
main: io.github.dionatestserver.pluginhooker.PluginHooker
softdepend: [ProtocolLib]
authors: [ Loyisa, Hellxd ]
description: PluginHooker
website: https://diona-testserver.github.io/
