name: PluginHooker
version: '${project.version}'
main: dev.diona.pluginhooker.PluginHooker
softdepend: [ProtocolLib]
authors: [ Loyisa, Hellxd ]
description: PluginHooker
website: https://github.com/DionaMC/PluginHooker
